version: "3"
services:
    apifinal:
        image: apifinal
        container_name: apifinal
        ports:
            - "3000:3000"
        depends_on:
            - dbfinal
    dbfinal:
        image: dbfinal
        container_name: dbfinal
        environment:
            ENV POSTGRES_USER: admin
            ENV POSTGRES_PASSWORD: 123456
            ENV POSTGRES_DB: horus
        ports:
            - "5432:5432"